### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by sapnii2** [ishalyminov/bag_of_words_classification#1]
Hi, can you please provide python version and dependencies for this code?
Thanks,

**Comment by ishalyminov** [comment]
Oh wow - it's been a while since I touched it last time. Apparently at the time I was unaware of `requirements.txt` 😅
So it's written in Python2.x (let's say 2.7), requirements that I can see are:
```
nltk
numpy
matplotlib
sklearn
```
Not sure at all about the specific version of each package.
If you get this to work for yourself, could you please PR your `requirements.txt` or dump `pip freeze` right here?
